hahu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/models.py
from django.db import models, connection
from django.utils import timezone
from django.utils.html import strip_tags
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from imagekit.models import ProcessedImageField
from datetime import datetime
from django.conf import settings
from django.contrib.sessions.models import Session
from django.contrib.auth.signals import user_logged_in

from hahu.settings import CACHE_CONTENT_LENGTH

import uuid
import logging

logger = logging.getLogger(__name__)


def _content_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (instance.inner_user.username, ext)
    return 'static/avatars/' + filename


class Profile(models.Model):
    UNKNOWN = 0
    MALE = 1
    FEMALE = 2

    free_time = models.DateTimeField(default=timezone.now)
    points = models.IntegerField(default=0)
    gender = models.IntegerField(default=0)
    inner_user = models.OneToOneField(User)
    first_name = models.CharField(max_length=10, default='')
    last_name = models.CharField(max_length=10, default='')
    avatar = models.ImageField(upload_to=_content_file_name, default='static/images/anonymous.jpg')
    self_intro = models.CharField(max_length=150, default='此用户太懒了，并没有填写个人介绍...')
    sign_time = models.DateField(default=datetime(1970, 1, 1))

    def __str__(self):
        return 'username: {}, nickname: {}, points: {}, gender: {}' \
            .format(self.inner_user.username, self.nickname, self.points, self.gender)

    @property
    def followers(self):
        return list(map(lambda r: r.from_user, U2URelationship
                        .objects.select_related('from_user')
                        .filter(to_user=self.inner_user, relationship=0).all()))

    @property
    def follower_names(self):
        return list(map(lambda r: r.from_user.username, U2URelationship
                        .objects.select_related('from_user')
                        .filter(to_user=self.inner_user, relationship=0).all()))

    @property
    def followees(self):
        return list(map(lambda r: r.to_user, U2URelationship
                        .objects.select_related('to_user')
                        .filter(from_user=self.inner_user, relationship=0).all()))

    def ban(self, days=1):
        self.free_time = timezone.now() + timezone.timedelta(days=days)


class UserSession(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    session = models.ForeignKey(Session)


def user_logged_in_handler(sender, request, user, **kwargs):
    UserSession.objects.get_or_create(user=user, session_id=request.session.session_key)


user_logged_in.connect(user_logged_in_handler)


def create_user(username, email, password, **kwargs):
    inner_user = User.objects.create_user(username, email, password)
    user_profile = Profile(inner_user=inner_user, **kwargs)
    user_profile.save()
    logger.info('create user', user_profile)
    return inner_user


def follow(from_user, user):
    if not user or from_user == user:
        return False

    _, created = U2URelationship.objects.get_or_create(from_user=from_user, to_user=user)
    return created


class Question(models.Model):
    __tablename__ = 'question'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, default='')
    content = models.TextField(default='')
    create_time = models.DateTimeField(default=timezone.now)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True)

    class Meta:
        ordering = ('-create_time',)

    def __str__(self):
        return 'title: {}, content: {}, create_time: {}, from_username: {}' \
            .format(self.title, self.content, self.create_time, self.from_user.username)

    @property
    def answers(self):
        return sorted(self.answer_set.all(), key=lambda x: -x.vote_num)


class Topic(models.Model):
    name = models.CharField(max_length=10, default='')
    descriptor = models.TextField(default='')
    questions = models.ManyToManyField(Question, related_name='topics')


class Answer(models.Model):
    __tablename__ = 'answer'

    id = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
    content = models.TextField(default='')
    from_user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    from_question = models.ForeignKey(Question, blank=True, on_delete=models.CASCADE, db_index=True)
    create_time = models.DateTimeField(default=timezone.now)
    edit_time = models.DateTimeField(default=timezone.now)

    @property
    def vote_num(self):
        return Vote.objects.filter(choice=0, to_answer=self).count()


class Comment(models.Model):
    content = models.CharField(max_length=100, default='')
    from_user = models.ForeignKey(User, related_name='user_comments')
    from_answer = models.ForeignKey(Answer, related_name='comments')


class Vote(models.Model):
    __tablename__ = 'vote'

    id = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
    # TODO: CharField | Choice
    # Vote up, Vote down, Thanks, Helpless
    create_time = models.DateTimeField(default=timezone.now)
    choice = models.IntegerField(default=0)
    to_answer = models.ForeignKey(Answer, blank=True, on_delete=models.CASCADE, db_index=True)
    from_user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE, db_index=True)

    unique_together = ('to_answer', 'from_user')


def newest_events(user, num=10):
    followees = user.profile.followees
    cnt = len(followees)
    if cnt == 0:
        return []
    query_sign = '=' if cnt == 1 else 'IN'
    followees_id_str = '(%s)' % ', '.join(map(lambda x: str(x.id), followees))

    with connection.cursor() as c:
        event_types = ['question', 'answer', 'vote']
        single_query_sql_template = \
            """
            SELECT id, create_time, from_user_id, "{}" AS table_name
            FROM polls_{}
            WHERE from_user_id {} {}
            """

        union_query_sql = '\nUNION\n'.join(
            [single_query_sql_template.format(t, t, query_sign, followees_id_str) for t in event_types])

        raw_sql = union_query_sql + \
                  """
                  ORDER BY create_time DESC
                  LIMIT {}
                  """.format(num)

        print(raw_sql)

        logger.info('raw sql', raw_sql)
        c.execute(raw_sql)

        results = c.fetchall()

    events = []
    for r in results:
        event_id, event_type = r[0], r[-1]
        events.append(({'question': Question,
                        'answer': Answer,
                        'vote': Vote,
                        })[event_type].objects.get(id=event_id))

    return events


def get_self_feeds(user, start=0, end=100):
    if start >= end:
        return []

    with connection.cursor() as c:
        event_types = ['question', 'answer', 'vote']
        single_query_sql_template = \
            """
            SELECT id, create_time, from_user_id, "{}" AS table_name
            FROM polls_{}
            WHERE from_user_id = {}
            """

        union_query_sql = '\nUNION\n'.join(
            [single_query_sql_template.format(t, t, user.id) for t in event_types])

        raw_sql = union_query_sql + \
                  """
                  ORDER BY create_time DESC
                  LIMIT {}, {}
                  """.format(start, end)

        print(raw_sql)

        logger.info('raw sql', raw_sql)
        c.execute(raw_sql)

        results = c.fetchall()

    feeds = []

    for r in results:
        event_id, event_type = r[0], r[-1]
        event = ({'question': Question,
                  'answer': Answer,
                  'vote': Vote,
                  })[event_type].objects.get(id=event_id)

        feed = dict(event_type=event_type,
                    feed_id=str(event.id),
                    create_time=event.create_time.timestamp(),
                    username=event.from_user.username,
                    avatar=event.from_user.profile.avatar.url)

        if event_type == 'question':
            feed.update(title=event.title,
                        question_id=str(event.id),
                        content=strip_tags(event.content)[:CACHE_CONTENT_LENGTH])
        elif event_type == 'answer':
            feed.update(title=event.from_question.title,
                        question_id=str(event.from_question.id),
                        content=strip_tags(event.content)[:CACHE_CONTENT_LENGTH])
        elif event_type == 'vote':
            feed.update(title=event.to_answer.from_question.title,
                        question_id=str(event.to_answer.from_question.id),
                        content=event.to_answer.content[:CACHE_CONTENT_LENGTH])

        feeds.append(feed)

    return feeds


def get_feeds(user, start=0, end=100):
    if start >= end:
        return []

    followees = user.profile.followees
    cnt = len(followees)
    if cnt == 0:
        return []
    query_sign = '=' if cnt == 1 else 'IN'
    followees_id_str = '(%s)' % ', '.join(map(lambda x: str(x.id), followees))

    with connection.cursor() as c:
        event_types = ['question', 'answer', 'vote']
        single_query_sql_template = \
            """
            SELECT id, create_time, from_user_id, "{}" AS table_name
            FROM polls_{}
            WHERE from_user_id {} {}
            """

        union_query_sql = '\nUNION\n'.join(
            [single_query_sql_template.format(t, t, query_sign, followees_id_str) for t in event_types])

        raw_sql = union_query_sql + \
                  """
                  ORDER BY create_time DESC
                  LIMIT {}, {}
                  """.format(start, end)

        print(raw_sql)

        logger.info('raw sql', raw_sql)
        c.execute(raw_sql)

        results = c.fetchall()

    feeds = []

    for r in results:
        event_id, event_type = r[0], r[-1]

polls/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        required=True,
        label=u'用户名',
        error_messages={'required': '请输入用户名'},
        widget=forms.TextInput(
            attrs={
                'placeholder': u'用户名',
            }
        ),
    )
    password = forms.CharField(
        required=True,
        label=u'密码',
        error_messages={'required': u'请输入密码'},
        widget=forms.PasswordInput(
            attrs={
                'placeholder': u'密码',
            }
        ),
    )

    def clean(self):
        if not self.is_valid():
            raise forms.ValidationError(u'用户名和密码为必填项')
        else:
            cleaned_data = super(LoginForm, self).clean()


class SignupForm(forms.Form):
    username = forms.CharField(
        required=True,
        label=u'用户名',
        error_messages={'required': '请输入用户名'},
        widget=forms.TextInput(
            attrs={
                'placeholder': u'用户名',
            }
        ),
    )
    password = forms.CharField(
        required=True,
        label=u'密码',
        error_messages={'required': u'请输入密码'},
        widget=forms.PasswordInput(
            attrs={
                'placeholder': u'密码',
            }
        ),
    )

    email = forms.EmailField(
        required=True,
        label=u'邮箱',
        error_messages={'required': u'请输入邮箱'},
        widget=forms.EmailInput(
            attrs={
                'placeholder': u'hahu@hahu.com'
            }
        )
    )

    def clean(self):
        if not self.is_valid():
            raise forms.ValidationError(u'用户名、密码和邮箱为必填项')
        else:
            cleaned_data = super(SignupForm, self).clean()

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="{% static "styles/roboto.css" %}">
  <link rel="stylesheet" href="{% static "styles/material.min.css" %}">
  <link rel="stylesheet" href="{% static "styles/materialdesignicons.min.css" %}">
  <link rel="stylesheet" href="{% static "styles/base.css" %}">

  {% block style %}

  {% endblock %}
</head>
<body>
{% block content %}

{% endblock %}

<script src="{% static "scripts/jquery-3.1.0.min.js" %}"></script>
<script src="{% static "scripts/material.min.js" %}"></script>
<script src="{% static "scripts/socket.io.min.js" %}"></script>
<script src="{% static "scripts/navbar.js" %}"></script>

{% block script %}

{% endblock %}
</body>
</html>

templates/chat.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  Chat
{% endblock %}

{% block style %}
  <link rel="stylesheet" href="{% static "styles/chat.css" %}">
{% endblock %}

{% block content %}
  {% include "navbar.html" %}

  <div id="message-box" class="flex-center">
    <div class="mdl-card mdl-shadow--4dp card">
      <template v-for="message in messages">
        <template v-if="message.type == 'get'">
          <div class="bubble-box">
            <div class="left-message bubble">
              $$ message.message $$
            </div>
          </div>
        </template>
        <template v-else>
          <div class="bubble-box">
            <div class="right-message bubble">
              $$ message.message $$
            </div>
          </div>
        </template>
      </template>

      <div id="input_box">
        <form id="form-id">
          <div class="mdl-textfield mdl-js-textfield">
            <input class="mdl-textfield__input" type="text" id="id_message" name="message">
            <label class="mdl-textfield__label" for="id_message">请输入消息...</label>
          </div>
          <button type="submit"
                  class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab mdl-js-ripple-effect mdl-button--colored">
            <i class="mdi mdi-send"></i>
          </button>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

{% block script %}
  <script src="{% static "scripts/vue.min.js" %}"></script>
  <script src="{% static "scripts/chat.js" %}"></script>
{% endblock %}

templates/comment.html
<div class="mdl-tabs__panel">
  <ul class="mdl-list list">
    {% for comment in comments %}
      <li class="mdl-list__item mdl-list__item--two-line">
    <span class="mdl-list__item-primary-content">
      <a href="/profile/{{ comment.from_user.username }}/" class="comment-circle">
        <img src="/{{ comment.from_user.profile.avatar }}" alt="Avatar">
      </a>
        <span>
            {{ comment.from_user.username }}
        </span>
        <br>
        <span class="mdl-list__item-text-body">
            {{ comment.content|striptags }}
        </span>
      </span>
      </li>
    {% endfor %}
  </ul>
</div>

templates/discover.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  Discover
{% endblock %}

{% block style %}
  <link rel="stylesheet" href="{% static "styles/discover.css" %}">
{% endblock %}

{% block content %}
  {% include "navbar.html" %}

  <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
    <div class="mdl-tabs__tab-bar">
      <a href="#questions-panel" class="mdl-tabs__tab is-active">Questions</a>
      <a href="#answers-panel" class="mdl-tabs__tab">Answers</a>
    </div>

    <div class="mdl-tabs__panel is-active" id="questions-panel">
      <ul class="mdl-list list">
        {% for question in questions %}
          <li class="mdl-list__item mdl-list__item--three-line">
            <span class="mdl-list__item-primary-content">
              <img src="/{{ question.from_user.profile.avatar }}" alt="Avatar" class="mdl-list__item-avatar">
              <span>{{ question.title }}</span>
              <span class="mdl-list__item-text-body">{{ question.content|striptags }}</span>
            </span>
            <span class="mdl-list__item-primary-content">
              <a href="/questions/{{ question.id }}/" class="mdl-list__item-secondary-action">
                <i class="mdi mdi-36px mdi-arrow-right-bold-circle"></i>
              </a>
            </span>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="mdl-tabs__panel" id="answers-panel">
      <ul class="mdl-list list">
        {% for answer in answers %}
          <li class="mdl-list__item mdl-list__item--three-line">
            <span class="mdl-list__item-primary-content">
              <img src="/{{ answer.from_user.profile.avatar }}" alt="Avatar" class="mdl-list__item-avatar">
              <span>{{ answer.from_question.title }} 问题中 {{ answer.from_user.username }} 的回答</span>
              <span class="mdl-list__item-text-body">{{ answer.content|striptags }}</span>
            </span>
            <span class="mdl-list__item-primary-content">
              <a href="/questions/{{ answer.from_question.id }}/" class="mdl-list__item-secondary-action">
                <i class="mdi mdi-36px mdi-arrow-right-bold-circle"></i>
              </a>
            </span>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>

{% endblock %}

{% block script %}

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  Ha Hu Θ..Θ
{% endblock %}

{% block style %}
  <link rel="stylesheet" href="{% static "styles/index.css" %}">
{% endblock %}

{% block content %}
  {% include "navbar.html" %}

  <div id="container">
    <ul class="mdl-list" id="feed-stream">
      <template v-for="feed in feeds">
        <li class="mdl-list__item mdl-list__item--three-line">
        <span class="mdl-list__item-primary-content">
          <a href="/profile/$$ feed.username $$/" class="circle">
            <img :src="'/' + feed.avatar" alt="Avatar">
          </a>
          <span>
            <a href="/profile/$$ feed.username $$/">$$ feed.username $$</a>
              <span v-if="feed.event_type == 'question'">提出了问题</span>
              <span v-if="feed.event_type == 'answer'">回答了问题</span>
              <span v-if="feed.event_type == 'vote'">点赞了回答</span>
            <br>
          <a href="/questions/$$ feed.question_id $$/">$$ feed.title $$</a>
          </span>
          <span class="mdl-list__item-text-body">
              $$$ feed.content $$$
          </span>
        </span>
          <span class="mdl-list__item-secondary-content">
          <span class="mdl-list__item-secondary-info">Detail</span>
          <a class="mdl-list__item-secondary-action" href="#">
            <i class="mdi mdi-36px mdi-arrow-right-bold-circle"></i>
          </a>
        </span>
        </li>
      </template>
    </ul>

    <div class="mdl-card" id="sign">
      <div class="mdl-card__title">
        <h2 class="mdl-card__title-text">续命</h2>
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <span v-if="is_signed">续命虽好&nbsp可不要贪杯哦...</span>
        <button v-else id="sign-btn" data-username="$$ cur_user $$"
                class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--white">
          +1s
        </button>
      </div>
    </div>
  </div>

{% endblock %}

{% block script %}
  <script src="{% static "scripts/vue.min.js" %}"></script>
  <script>
    var csrf_token = '{{ csrf_token }}';
  </script>
  <script src="{% static "scripts/index.js" %}"></script>
{% endblock %}

templates/settings.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  设置
{% endblock %}

{% block style %}
  <link rel="stylesheet" href="{% static "styles/settings.css" %}">
{% endblock %}

{% block content %}
  {% include 'navbar.html' %}
  <form action method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mdl-layout mdl-layout--fixed-header mdl-js-layout mdl-color--white-100">
      <main class="mdl-layout__content main_content">
        <div class="form-div mdl-grid mdl-shadow--2dp">
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-account"></i>
            用户名：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="text" id="id_username" name="username"
                     value="{{ cur_user.username }}" disabled>
              <label class="mdl-textfield__label" for="id_username">用户名无法修改</label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-account"></i>
            姓：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="text" id="id_last_name" name="last_name"
                     value="{{ cur_user.profile.last_name }}">
              <label class="mdl-textfield__label" for="id_last_name">输入您的姓氏...</label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-account"></i>
            名：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="text" id="id_first_name" name="first_name"
                     value="{{ cur_user.profile.first_name }}">
              <label class="mdl-textfield__label" for="id_first_name">输入您的名字...</label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-lock"></i>
            密码：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="password" id="id_password" name="password">
              <label class="mdl-textfield__label" for="id_password">输入新密码...</label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-email"></i>
            邮箱：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="email" id="id_email" name="email" value="{{ cur_user.email }}">
              <label class="mdl-textfield__label" for="id_email">请输入您的邮箱...</label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-information"></i>
            简介：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="text" id="id_intro" name="intro"
                     value="{{ cur_user.profile.self_intro }}">
              <label class="mdl-textfield__label" for="id_intro">请填写您的个人介绍...</label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-gender-male-female"></i>
            性别：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <label class="mdl-radio mdl-js-radio" for="id_male">
                <input type="radio" id="id_male" name="gender" class="mdl-radio__button"
                       {% if cur_user.profile.gender == 1 %}checked{% endif %} value="1">
                <span class="mdl-radio__label">Male</span>
              </label>
              <label class="mdl-radio mdl-js-radio" for="id_female">
                <input type="radio" id="id_female" name="gender" class="mdl-radio__button"
                       {% if cur_user.profile.gender == 2 %}checked{% endif %} value="2">
                <span class="mdl-radio__label">Female</span>
              </label>
              <label class="mdl-radio mdl-js-radio" for="id_secret">
                <input type="radio" id="id_secret" name="gender" class="mdl-radio__button"
                       {% if cur_user.profile.gender == 0 %}checked{% endif %} value="0">
                <span class="mdl-radio__label">Secret</span>
              </label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--6-col" id="fileInput">
            <i class="mdi mdi-24px mdi-image"></i>
            头像：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--file">
              <input class="mdl-textfield__input" placeholder="File" type="text" id="uploadFile" readonly/>
              <div class="mdl-button mdl-button--primary mdl-button--icon mdl-button--file">
                <i class="mdi mdi-attachment"></i>
                <input type="file" id="uploadBtn" name="avatar">
              </div>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col btn-con">
            <button type="submit"
                    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary btn">
              Save
            </button>
          </div>
        </div>
      </main>
    </div>
  </form>
{% endblock %}

{% block script %}
  <script src="{% static "scripts/settings.js" %}"></script>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  Signup
{% endblock %}

{% block style %}
  <link rel="stylesheet" href="{% static "styles/signup.css" %}">
{% endblock %}

{% block content %}

  <form action method="post">
    {% csrf_token %}
    <div class="mdl-layout mdl-layout--fixed-header mdl-js-layout  mdl-color--white-100">
      <main class="mdl-layout__content main_content">
        <div class="login-form-div mdl-grid mdl-shadow--2dp">
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <h3><strong>Sign up</strong></h3>
          </div>
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-account"></i>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="text" id="id_username" name="username">
              <label class="mdl-textfield__label" for="id_username">Enter valid Username</label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-lock"></i>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="password" id="id_password" name="password">
              <label class="mdl-textfield__label" for="id_password">Enter Password</label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col cell_con">
            <i class="mdi mdi-24px mdi-email"></i>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
              <input class="mdl-textfield__input" type="email" id="id_email" name="email">
              <label class="mdl-textfield__label" for="id_email">Enter Email</label>
            </div>
          </div>
          <div class="mdl-cell mdl-cell--12-col login-btn-con">
            <button type="submit"
                    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary btn">
              Sign up
            </button>
          </div>
          <div class="mdl-cell mdl-cell--6-col mdl-cell--8-col-tablet links">
            <a href="/accounts/login/" class="mdl-button--primary">Log in now !</a>
          </div>
        </div>
      </main>
    </div>
  </form>
  <canvas id="canvas"></canvas>

{% endblock %}

{% block script %}
  <script src="{% static "scripts/dotbackground.js" %}"></script>
  <script src="{% static "scripts/signup.js" %}"></script>
{% endblock %}